# Turn on validation, so we can use import:
version: ~> 1.0

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

script:
- (cd api;       APPMAP=true bundle exec rspec)
- (cd backend;   APPMAP=true bundle exec rspec)
- (cd core;      APPMAP=true bundle exec rspec)
- (cd frontend;  APPMAP=true bundle exec rspec)


after_script:
- env DEBUG=true ruby ./upload-appmaps  */tmp/appmap/rspec
