# Turn on validation, so we can use import:
version: ~> 1.0

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

addons:
  chrome: stable

# installation instructions for chrome driver found from
# https://amihaiemil.com/2017/07/14/selenium-headless-chrome-travis.html
install:
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver

script:
- cd api;      APPMAP=true bundle exec rspec; cd ..
- cd backend;  APPMAP=true bundle exec rspec; cd ..
- cd core;     APPMAP=true bundle exec rspec; cd ..
- cd frontend; APPMAP=true bundle exec rspec; cd ..

after_script:
- env DEBUG=true ruby ./upload-appmaps api/tmp/appmap/rspec
- env DEBUG=true ruby ./upload-appmaps backend/tmp/appmap/rspec
- env DEBUG=true ruby ./upload-appmaps core/tmp/appmap/rspec
- env DEBUG=true ruby ./upload-appmaps frontend/tmp/appmap/rspec
