# Turn on validation, so we can use import:
version: ~> 1.0

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

addons:
  apt:
    packages:
    - parallel

# script: |
#   run_tests() (
#     cd $1
#     # Use -f doc so we get regular output and keep Travis happy
#     APPMAP=true bundle exec rspec -f doc || true
#   )
#   export -f run_tests
#   echo 'api backend core frontend' | parallel -j3 --will-cite --line-buffer -d ' ' run_tests

env:
  global:
  - EXTRA_APPMAPS="*/tmp/appmap/rspec"

# install selenium chrome driver instructions from
# https://github.com/yizeng/setup-selenium-webdriver-ruby-project-on-travis-ci/blob/master/.travis.yml

jobs:
  include:
  - stage: test
    workspaces:
      create:
        name: appmaps
        paths:
        - "$EXTRA_APPMAPS"
    before_script: |
      install_selenium() (
        gem install selenium-webdriver
        wget -N https://chromedriver.storage.googleapis.com/85.0.4183.38/chromedriver_linux64.zip -P ~/Downloads
        unzip ~/Downloads/chromedriver_linux64.zip -d ~/Downloads
        sudo mv -f ~/Downloads/chromedriver /usr/local/share/
        sudo chmod +x /usr/local/share/chromedriver
        sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
        sudo ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
      )
    script: |
      run_tests() (
        cd $1
        # Use -f doc so we get regular output and keep Travis happy
        APPMAP=true bundle exec rspec -f doc || true
      )
      export -f run_tests
      echo 'api backend core frontend' | parallel --will-cite --line-buffer -d ' ' run_tests
    after_script:
    - true
  - stage: upload
    workspaces:
      use:
      - appmaps
    install:
    - true
    script:
    - true
