# Turn on validation, so we can use import:
version: ~> 1.0

import:
- land-of-apps/land-of-apps:travis/ruby-imports.yml

addons:
  apt:
    packages:
    - parallel

script: |
  run_tests() (
    cd $1
    # Use -f doc so we get regular output and keep Travis happy
    APPMAP=true bundle exec rspec -f doc || true
  )
  export -f run_tests
  echo 'api backend core frontend' | parallel --will-cite --line-buffer -d ' ' run_tests

env:
  global:
  - EXTRA_APPMAPS="*/tmp/appmap/rspec"
